trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none
- script: |
    echo "Cloning repository..."
    git clone -v https://github.com/Oseberg-Solutions/PCF-Component.git
    cd PCF-Component
    echo "Pushing to Azure DevOps..."
    git push --mirror -v "https://sub@oseberg.com@dev.azure.com/OsebergCRM/CRM%20-%20Proff%20(Firma%20Søk)/_git/PCF-Component"
