# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none
- script: |
    git clone https://github.com/Oseberg-Solutions/PCF-Component.git
    git push https://sub@oseberg.com@dev.azure.com/OsebergCRM/CRM%20-%20Proff%20(Firma%20Søk)/_git/PCF-Component --all