import { CompanyData } from "./interfaces/CompanyData";

export const testData: CompanyData[]= [
  {
    name: "OSEBERG SOLUTIONS AS",
    organisationNumber: "981586581",
    email: "",
    homePage: "http://www.oseberg.no",
    mobilePhone: "",
    telephoneNumber: "48086000",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD OSLO",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "",
    addressLine: "Karl Johans gate 25",
    boxAddressLine: "",
    postPlace: "Oslo",
    zipCode: "0159",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD TØNSBERG",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "48086000",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "OSEBERG SOLUTIONS SE",
    organisationNumber: "981586581",
    email: "",
    homePage: "http://www.oseberg.no",
    mobilePhone: "",
    telephoneNumber: "48086000",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD Danmark",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "",
    addressLine: "Karl Johans gate 25",
    boxAddressLine: "",
    postPlace: "Oslo",
    zipCode: "0159",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD TØNSBERG Danmark",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "48086000",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
];
