import { CompanyData } from "./interfaces/CompanyData";

export const testData: CompanyData[]= [
  {
    name: "OSEBERG SOLUTIONS AS",
    organisationNumber: "981586581",
    email: "post@oseberg.no",
    homePage: "http://www.oseberg.no",
    mobilePhone: "",
    telephoneNumber: "48086000",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD OSLO",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "",
    addressLine: "Karl Johans gate 25",
    boxAddressLine: "",
    postPlace: "Oslo",
    zipCode: "0159",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD TØNSBERG",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "48086000",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "OSEBERG SOLUTIONS SE",
    organisationNumber: "981586581",
    email: "",
    homePage: "http://www.oseberg.no",
    mobilePhone: "",
    telephoneNumber: "1",
    addressLine: "Grev Wedels gate 12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD Danmark",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "3",
    addressLine: "Karl Johans gate 25",
    boxAddressLine: "",
    postPlace: "Oslo",
    zipCode: "0159",
  },
  {
    name: "OSEBERG SOLUTIONS AS AVD TØNSBERG Danmark",
    organisationNumber: "981586581",
    email: "",
    homePage: "",
    mobilePhone: "",
    telephoneNumber: "2",
    addressLine: "G12",
    boxAddressLine: "",
    postPlace: "Tønsberg",
    zipCode: "3111",
  },
  {
    name: "Suran AS",
    organisationNumber: "981586554",
    email: "sub@oseberg.no",
    homePage: "www.hypestudio.no",
    mobilePhone: "",
    telephoneNumber: "92216836",
    addressLine: "Hotvetveien 37R",
    boxAddressLine: "",
    postPlace: "Drammen",
    zipCode: "3018",
  },
];
